### ISSUE TITLE
Arreglar problemas en la master con travis.

### ISSUE THREAD

**Issue by AlexBarreraSanchez** [Arquisoft/InciDashboard_e5a#10]
Travis es incapaz de hacer un build del proyecto. Hay que solucionarlo.

**Comment by UO204115** [comment]
Me pongo a trabajar en ello

**Comment by UO204115** [comment]
El error anterior ya está corregido y ya avanza desde este punto, pero se engancha después al ejecutar la siguiente instrucción:
./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

El problema está en la instrucción en sí misma ya que debería ser **mvn** y no **mvnw** pero no localizo el fichero con la instrucción para corregirla

**Comment by UO204115** [comment]
Corregido ese error, venía de dos scripts, borrándolos ya avanza el build pero los dejaré en una carpeta dentro del proyecto scripts_error_build por si fuese necesario recuperarlos

**Comment by UO204115** [comment]
Finalmente error corregido, ya funciona la integración continua
