### ISSUE TITLE
Crear una primera prueba de ejemplo con cucumber.

### ISSUE THREAD

**Issue by AlexBarreraSanchez** [Arquisoft/InciDashboard_e5a#12]
Hay que añadir las dependencias necesarias para usar cucumber y crear una primera prueba de ejemplo. Esta primera prueba debería tener varios comentarios para explicar como se ha hecho y así facilitar la implementación de las siguientes pruebas.

**Comment by TaniaAlvarezDiaz** [comment]
He añadido al archivo pom la dependencia correspondiente y he creado en la carpeta "src/test/java/cucumber.feature" un archivo feature con la prueba de login del administrador

**Comment by TaniaAlvarezDiaz** [comment]
He actualizado dicha prueba para añadir un nuevo escenario que pruebe el inicio de sesion de un usuario que no es administrador.
Estoy investigando como poder probar dicha prueba.

**Comment by TaniaAlvarezDiaz** [comment]
He creado la clase de test LoginSteps con tres metodos, los cuales muestran la lista de usuarios proporcionada, el email del usuario que inicia sesion y el mensaje de inicio de sesion respectivamente.
Falta probar si funciona correctamente.
