### ISSUE TITLE
Permitir visualizar en un mapa las incidencias.

### ISSUE THREAD

**Issue by AlexBarreraSanchez** [Arquisoft/InciDashboard_e5a#3]
Se ofrecerá la posibilidad de visualizar las incidencias geolocalizadas en un mapa.

**Comment by UO204115** [comment]
Estoy investigando ya cómo añadir los mapas

**Comment by TaniaAlvarezDiaz** [comment]
He añadido en "src/main/resources/templates" el html map donde se encuentra una plantilla que nos puede servir para visualizar el mapa.
Estoy analizandola para modificarla acorde a nuestras necesidades

**Comment by TaniaAlvarezDiaz** [comment]
He creado la API Key. Sigo investigando como pasarle la lista de incidencias.

**Comment by TaniaAlvarezDiaz** [comment]
He conseguido mostrar una incidencia en el mapa
