### ISSUE TITLE
Arreglar problemas con el coverage.

### ISSUE THREAD

**Issue by AlexBarreraSanchez** [Arquisoft/InciDashboard_e5a#9]
Solucionar problemas con la etiqueta coverage.

**Comment by UO204115** [comment]
Error de Travis corregido y añadido lo necesario para que funcione el codecov, cuando se resuelva el fallo de la BD debería funcionar sin problemas

**Comment by AlexBarreraSanchez** [comment]
He cambiado el plugin a <build>

**Comment by AlexBarreraSanchez** [comment]
Ya está solucionado. Procedo a cerrar el issue.
